### ISSUE TITLE
Docker container crashes without any error

### ISSUE THREAD

**Issue by Nitwel** [mallorbc/stable-diffusion-klms-gui#5]
This is on windows using WSL. When trying to run the `./run_image.sh` I get no error and the container just disappears without any error message.

https://user-images.githubusercontent.com/22577866/188948826-fc6acfbd-78ee-45d1-8628-b2211010e2f7.mp4

**Comment by frozdbyte** [comment]
+1

**Comment by Batman313v** [comment]
This looks extremely similar to an issue I was having where the model.ckpt couldn't be found. I only discovered this was the problem by manually executing the web_gui.py script the dockerfile attempts to execute after the wgets. I took a number of steps to fix this and am not 100% sure what step did it. 
### First thing
I would recommend opening the files in a text editor (I use atom) and changing the line endings to use UNIX style instead of Windows style for the `docker/Dockerfile`.

_In atom this is located in the bottom right and will be set to CRLF. Change this to LF. You may need to install the line endings package_
### The second thing 
I'm not the biggest fan of using a script file to start my container so I used a docker compose file. My docker-compose.yml file is as follows.

_Save this in the docker folder from the repo_
```yaml
version: "3.9"
services:
  sd:
    # build: .
    image: stable_diffusion1v4:latest
    ports:
      - "7860:7860"
    volumes:
      - ../diffusion_model:/app/models/ldm/stable-diffusion-v1/
      - ../outputs:/app/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
To get the `stable_diffusion1v4:latest` :

1. I commented out the `image:` line and uncommented the `build: .` line to run the build first. 
2. I then used the `docker commit {docker_id} {container_name}` command to save the running container after downloads were complete. _This is doing the same thing as the save_container.sh file in the docker folder._ 
3. Then comment the `build: .` and uncomment the `image: ` and that's how I got it running.

**NOTE: This has only been tested on windows with wsl 2.0 you may experience different results with different setups**

**Comment by Nitwel** [comment]
This is what I get now using your docker compose file.
```
nitwel@Nils-PC:~/Dev/StableDiffusion/stable-diffusion-klms-gui/docker$ docker compose up
[+] Running 1/0
 ⠿ Container docker-sd-1  Created                                                                                                                                                                                                                                                    0.0s
Attaching to docker-sd-1
docker-sd-1  | /usr/local/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
docker-sd-1  |   warnings.warn(
docker-sd-1  | /usr/local/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
docker-sd-1  |   warnings.warn(msg)
docker-sd-1 exited with code 137
```

Could it be that I don't have enough RAM? I have 16GB but it spikes to 100% usage while running the command.

Here's a graph on how the memory usage spikes.
![grafik](https://user-images.githubusercontent.com/22577866/189077613-abc47a97-1cc0-4382-a96e-7aec88de6299.png)

**Comment by frozdbyte** [comment]
This might really be an issue with memory.
When running the normal run_image.sh, I also get a memory spike to the max of 16 GB and then a crash without any error.
After minimizing the memory usage of my pc by closing all applications, the container runs more downloads than before but still crashes when maxing out the memory.
![image](https://user-images.githubusercontent.com/59323943/189131086-4eb42c7c-a502-4071-bad5-7ae7193665f1.png)

**Comment by Batman313v** [comment]
That would definitely cause it to crash. The lowest hardware I run ML models on has 64gb and it sits around 43% while installing and around 40% once it's done. You should be able to use 32gb of ram based off these numbers as long as you don't have too many other things open in the background.

**Comment by Nitwel** [comment]
Good that I just orderd two more ram sticks to reach that number 😅. I'll write an update after if that fixes the problem.

Though it should be also looked into making the docker not crash / give a proper error message or even fix the docker from crashing as I was able to run another implementation of stable-diffusion just fine on 16GB of ram.

**Comment by Manuelbaun** [comment]
I got the docker container up an running on windows wsl2 ubuntu version 20.04. But as soon as I try to generate something, the docker container crashes and I dont get any errors:

```
/usr/local/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Loaded GFPGAN
Loaded RealESRGAN with model RealESRGAN_x4plus
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
[MemMon] Recording max memory usage...

Iteration: 1/1
morgen freeman
  0%|          | 0/50 [00:01<?, ?it/s]
```

**Comment by Batman313v** [comment]
> I got the docker container up an running on windows wsl2 ubuntu version 20.04. But as soon as I try to generate something, the docker container crashes and I dont get any errors:
> 
> ```
> /usr/local/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
>   warnings.warn(
> /usr/local/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
>   warnings.warn(msg)
> Loaded GFPGAN
> Loaded RealESRGAN with model RealESRGAN_x4plus
> Loading model from models/ldm/stable-diffusion-v1/model.ckpt
> Global Step: 470000
> LatentDiffusion: Running in eps-prediction mode
> DiffusionWrapper has 859.52 M params.
> making attention of type 'vanilla' with 512 in_channels
> Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
> making attention of type 'vanilla' with 512 in_channels
> Running on local URL:  http://0.0.0.0:7860
> 
> To create a public link, set `share=True` in `launch()`.
> [MemMon] Recording max memory usage...
> 
> Iteration: 1/1
> morgen freeman
>   0%|          | 0/50 [00:01<?, ?it/s]
> ```

How much RAM does your container have access to? I would also recommend trying this with [Docker Desktop](https://www.docker.com/products/docker-desktop/) as I am not sure how Windows would give WSL Ubuntu access to the CUDA drivers or GPU as I have not tried it. Where the model loaded it seems like it access the CUDA drivers just fine but I have no way to verify this. For the Docker Desktop you have to specify the access to the Nvidia GPU with 
```Yaml
deploy:
  resources:
    reservations:
      devices:
       - driver: nvidia
         count: 1
         capabilities: [gpu]
```
Or the container will fail. Using a docker compose file also seems to give error codes when failing instead of just crashing out. If you would like to use the Ubuntu install I would try using a docker compose file anyways and see if it will give you an error message

**Comment by Nitwel** [comment]
Can confirm that this was a memory issue. After upgrading to 32GB it works.

**Comment by Batman313v** [comment]
@Nitwel @Manuelbaun @frozdbyte 

Check out the [sd-webui](https://github.com/sd-webui/stable-diffusion-webui). It seems to be better optimized using around 10GB and installed without any modification. The repo is pretty new as it was migrated from a previous version so the documentation isn't all the way there yet. Here is the info for a [Docker installation](https://github.com/sd-webui/stable-diffusion-webui/discussions/922)
